name: detectree
channels:
  - conda-forge
dependencies:
  - affine
  - click
  - contextily
  - dask
  - detectree
  - geopandas
  - jupyter
  - laspy<2.0.0
  - matplotlib
  - numpy
  - osmnx
  - pandas
  - pip
  - pip:
    - -e .
  - python=3.7
  - rasterio
  - scipy
  - shapely
  - tqdm
